version: '3.8'
services:
  backend:
    build: .
    environment:
      STAGE: test
    command: 'python main.py runserver 0.0.0.0:8000'
    networks:
      - default
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app/app
    restart: always
